// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SinqiaParibas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241125014115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SinqiaMVC.Models.MovimentoManual", b =>
                {
                    b.Property<int>("DAT_MES")
                        .HasColumnType("int");

                    b.Property<int>("DAT_ANO")
                        .HasColumnType("int");

                    b.Property<int>("NUM_LANCAMENTO")
                        .HasColumnType("int");

                    b.Property<string>("COD_COSIF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("COD_PRODUTO")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("COD_USUARIO")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("DAT_MOVIMENTO")
                        .HasColumnType("datetime2");

                    b.Property<string>("DES_DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("VAL_VALOR")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DAT_MES", "DAT_ANO", "NUM_LANCAMENTO");

                    b.HasIndex("COD_PRODUTO", "COD_COSIF");

                    b.ToTable("MOVIMENTO_MANUAL", (string)null);
                });

            modelBuilder.Entity("SinqiaMVC.Models.Produto", b =>
                {
                    b.Property<string>("COD_PRODUTO")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("DES_PRODUTO")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("STA_STATUS")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("COD_PRODUTO");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("SinqiaMVC.Models.ProdutoCosif", b =>
                {
                    b.Property<string>("COD_PRODUTO")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("COD_COSIF")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("COD_CLASSIFICACAO")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("STA_STATUS")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("COD_PRODUTO", "COD_COSIF");

                    b.ToTable("PRODUTO_COSIF", (string)null);
                });

            modelBuilder.Entity("SinqiaMVC.Models.MovimentoManual", b =>
                {
                    b.HasOne("SinqiaMVC.Models.ProdutoCosif", "ProdutoCosif")
                        .WithMany("MovimentosManuais")
                        .HasForeignKey("COD_PRODUTO", "COD_COSIF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoCosif");
                });

            modelBuilder.Entity("SinqiaMVC.Models.ProdutoCosif", b =>
                {
                    b.HasOne("SinqiaMVC.Models.Produto", "Produto")
                        .WithMany("ProdutoCosifs")
                        .HasForeignKey("COD_PRODUTO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SinqiaMVC.Models.Produto", b =>
                {
                    b.Navigation("ProdutoCosifs");
                });

            modelBuilder.Entity("SinqiaMVC.Models.ProdutoCosif", b =>
                {
                    b.Navigation("MovimentosManuais");
                });
#pragma warning restore 612, 618
        }
    }
}
